[kbsnews_factcheck]
title = "KBS뉴스 ─ 팩트체크K"
url = "https://news.kbs.co.kr/news/list.do?mcd=1032"
entrySelector = "ul.list-type.list-thumb li"
titleSelector = "em.tit"
linkSelector = "a"
contentSelector = "span.script"
imageSelector = "span.img-center img"
waitUntil = "networkidle"

[sbsnews_fact]
title = "SBS뉴스 ─ 사실은"
url = "https://news.sbs.co.kr/news/fact.do"
entrySelector = "ul.type_thumb li"
titleSelector = "strong"
linkSelector = "a"
imageSelector = "span.thumb img"
contentSelector = "a.reporter"
waitUntil = "networkidle"

[mbcnews_turnedout]
title = "MBC뉴스 ─ 알고보니"
url = "https://news.imbc.com/newszoomin/turnedout/"
entrySelector = "ul.thumb_type.list_thumb_c li.item"
titleSelector = "span[class^='tit ellipsis']"
linkSelector = "a"
imageSelector = "span.img.ico_vod img"
contentSelector = "span.sub2"
waitUntil = "networkidle"